name: Build Flutter APK

on:
  push:
    branches:
      - develop

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build the APK
      - name: Build APK
        run: flutter build apk --release

      # Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # Generate a link to the APK in the README.md file
      - name: Generate APK link in README
        run: |
          echo "## Download APK" >> README.md
          echo "[Download the latest APK](./releases/download/release-apk/app-release.apk)" >> README.md
